#ifndef EDB_BRIDGE_CONFIG_H
#define EDB_BRIDGE_CONFIG_H

#ifndef EDB_BRIDGE_MAX_LINE
#define EDB_BRIDGE_MAX_LINE 512
#endif

#ifndef EDB_BRIDGE_ENABLE_TRANSPORT_CRYPTO
#if defined(ESP32)
#define EDB_BRIDGE_ENABLE_TRANSPORT_CRYPTO 1
#else
#define EDB_BRIDGE_ENABLE_TRANSPORT_CRYPTO 0
#endif
#endif

#ifndef EDB_BRIDGE_ENABLE_BASE64
#define EDB_BRIDGE_ENABLE_BASE64 1
#endif

#define EDB_BRIDGE_VERSION "1.0.0"
#define SD_PIN 5
#define TABLE_SIZE 8192
#define DEFAULT_REC_SIZE 8

#endif
